CREATE TABLE "TBL1" (
	"FLD1"	TEXT,
	"FLD2"	TEXT,
	"FLD3"	TEXT,
	PRIMARY KEY("FLD1")
);

INSERT INTO "TBL1" VALUES('1','A','abc');
INSERT INTO "TBL1" VALUES('2','B','def');
INSERT INTO "TBL1" VALUES('3','C','ghi');
